/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Activity2RouteImport } from './routes/activity-2'
import { Route as Activity1RouteImport } from './routes/activity-1'
import { Route as IndexRouteImport } from './routes/index'

const Activity2Route = Activity2RouteImport.update({
  id: '/activity-2',
  path: '/activity-2',
  getParentRoute: () => rootRouteImport,
} as any)
const Activity1Route = Activity1RouteImport.update({
  id: '/activity-1',
  path: '/activity-1',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity-1': typeof Activity1Route
  '/activity-2': typeof Activity2Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity-1': typeof Activity1Route
  '/activity-2': typeof Activity2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity-1': typeof Activity1Route
  '/activity-2': typeof Activity2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/activity-1' | '/activity-2'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/activity-1' | '/activity-2'
  id: '__root__' | '/' | '/activity-1' | '/activity-2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Activity1Route: typeof Activity1Route
  Activity2Route: typeof Activity2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/activity-2': {
      id: '/activity-2'
      path: '/activity-2'
      fullPath: '/activity-2'
      preLoaderRoute: typeof Activity2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity-1': {
      id: '/activity-1'
      path: '/activity-1'
      fullPath: '/activity-1'
      preLoaderRoute: typeof Activity1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Activity1Route: Activity1Route,
  Activity2Route: Activity2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
